CREATE USER 'adminMesonSagradaFamilia'@'%' IDENTIFIED BY 'm€s0nS4gradaF4milia2024$';GRANT ALL PRIVILEGES ON *.* TO 'adminMesonSagradaFamilia'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON `mesonsagradafamilia`.* TO 'adminMesonSagradaFamilia'@'%';

